services:
  data-fetcher:
    build: ./cron
    platform: linux/amd64
    volumes:
      - ./Data:/app/Data
    restart: unless-stopped

  shiny-app-1:
    build: ./shiny-app-1
    platform: linux/amd64
    ports:
      - "3838:3838"
    volumes:
      - ./Data:/srv/shiny-server/Data
    restart: unless-stopped

  shiny-app-2:
    build: ./shiny-app-2
    platform: linux/amd64
    ports:
      - "3839:3838"
    volumes:
      - ./Data:/srv/shiny-server/Data
    restart: unless-stopped