services:
  shinyproxy:
    image: openanalytics/shinyproxy
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy/application.yml:/opt/shinyproxy/application.yml
    networks:
      - sp-net

  data-fetcher:
    build: ./cron
    platform: linux/amd64
    volumes:
      - ./Data:/app/Data
    restart: unless-stopped
    networks:
      - sp-net

  shiny-app-1:
    build: ./shiny-app-1
    platform: linux/amd64
    volumes:
      - ./Data:/srv/shiny-server/Data
    networks:
      - sp-net

  shiny-app-2:
    build: ./shiny-app-2
    platform: linux/amd64
    volumes:
      - ./Data:/srv/shiny-server/Data
    networks:
      - sp-net

networks:
  sp-net:
    name: sp-net