proxy:
  title: Stone Living Lab Dashboards
  port: 8080
  container-wait-time: 60000
  hide-navbar: true
  body-classes:
    - shinyproxy-layout-grid
    - shinyproxy-layout-grid-3-columns

  authentication: none

  docker:
    url: unix:///var/run/docker.sock
    internal-networking: true 

  specs:
    - id: SLL_Flood_Dashboard
      display-name: SLL Flood Dashboard
      description: Dashboard for current flood conditions
      container-image: sll-shiny-app-1:latest
      container-port: 3838
      container-path: /app/  
      minimum-seats-available: 4
      seats-per-container: 4
      container-network: sp-net 
      pull-policy: IfNotPresent
    
      container-volumes:
         - /root/apps/sll_shiny/SLL_Shiny_Dashboard/Data:/srv/shiny-server/Data

    - id: SLL_Current_Coastal_Conditions
      display-name: SLL Current Coastal Conditions
      description: Dashboard of current coastal conditions
      container-image: sll-shiny-app-2:latest
      container-port: 3838
      container-path: /app/  
      minimum-seats-available: 4
      seats-per-container: 4
      container-network: sp-net 
      pull-policy: IfNotPresent

      container-volumes:
         - /root/apps/sll_shiny/SLL_Shiny_Dashboard/Data:/srv/shiny-server/Data

    - id: SLL_Storm_Explorer
      display-name: SLL Storm Explorer
      description: Dashboard to explore storms
      container-image: sll-shiny-app-3:latest
      container-port: 3838
      container-path: /app/  
      minimum-seats-available: 1
      seats-per-container: 1
      container-network: sp-net 
      pull-policy: IfNotPresent

      container-volumes:
         - /root/apps/sll_shiny/SLL_Shiny_Dashboard/Data:/srv/shiny-server/Data
 
    - id: Wicked_High_Tides
      display-name: Wicked High Tides
      description: App to explore Wicked High Tide impacts
      container-image: sll-shiny-app-4:latest
      container-port: 3838
      container-path: /app/  
      minimum-seats-available: 1
      seats-per-container: 5
      container-network: sp-net 
      pull-policy: IfNotPresent

      container-volumes:
         - /root/apps/sll_shiny/SLL_Shiny_Dashboard/Data:/srv/shiny-server/Data