proxy:
  title: Stone Living Lab Shiny Apps
  port: 8080

  authentication: none

  docker:
    url: unix:///var/run/docker.sock

  specs:
    - id: SLL_Flood_Dashboard
      display-name: SLL Flood Dashboard
      description: Dashboard for flood conditions
      build: sll_shiny_dashboard
      container-image: shiny-app-1 
      container-port: 3838
      pull-policy: IfNotPresent

    - id: SLL_Current_Coastal_Conditions
      display-name: SLL Current Coastal Conditions
      description: Dashboard of current coastal conditions
      build: sll_shiny_dashboard
      container-image: shiny-app-2
      container-port: 3838
      pull-policy: IfNotPresent